### ISSUE TITLE
Installation Issues 

### ISSUE THREAD

**Issue by randywreed** [johnwalicki/TJBot-Node-RED#1]
the npm install command in the readme generates this error:
```
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-red-contrib-speakerpi/node_modules/speaker/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/node-red-contrib-speakerpi/node_modules/speaker/.node-gyp/8.4.0"
```

This is apparently a reported error for .node-gyp. The workaround is to add --unsafe-perm before -g in the install command thus:
 `sudo npm --unsafe-perm -g install node-red-node-watson node-red-dashboard node-red-contrib-camerapi node-red-node-base64 node-red-contrib-play-audio node-red-contrib-micropi node-red-node-pi-neopixel node-red-node-weather-underground node-red-contrib-speakerpi`

With the addition of --unsafe-perm the package installs correctly.

**Comment by johnwalicki** [comment]
Thanks for the suggestion.  I've modified the README.md to include --unsafe-perm
Closed by [b359982](https://github.com/johnwalicki/TJBot-Node-RED/commit/b3599823e41ad62b85c203c92735c2f18e8a5d9f)
