### ISSUE TITLE
unknown: ui_button

### ISSUE THREAD

**Issue by imv7** [johnwalicki/TJBot-Node-RED#2]
![714733163305dcbb](https://user-images.githubusercontent.com/13357603/32961934-b05bc54a-cbb1-11e7-9506-494441cf6138.jpg)

**Comment by imv7** [comment]
![7d7be8418240c919](https://user-images.githubusercontent.com/13357603/32961993-dde91d46-cbb1-11e7-8c3e-488b39e7eeb9.jpg)

**Comment by johnwalicki** [comment]
Hi Install two additional packages
node-red-dashboard
node-red-node-base64

**Comment by johnwalicki** [comment]
I provide setup details in the "Node-RED Dependencies and Install Instructions" section at the bottom of the README.md

**Comment by imv7** [comment]
It worked! I thought I had installed everything. Thank you great flows!!!! Do you have more?

**Comment by johnwalicki** [comment]
Thanks - Glad you found them useful. Yes, I have more TJBot flows. My newest is a Hey Watson flow that is similar to Alexa. Will post them in the upcoming weeks.
